inventori/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('auth/',include('authentication.urls'))
]

main/urls.py
from django.urls import path
from .views import *

app_name='main'

urlpatterns = [
    path('', main, name='main'),
    path('add-vehicle/', add_vehicle, name='add_vehicle'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register, name='register'),
    path('all-vehicle-json/', get_all_vehicle_json, name='get_all_vehicle_json'),
    path('all-vehicle-xml/', get_all_vehicle_xml, name='get_all_vehicle_xml'),
    path('all-vehicles-json/', get_all_vehicle_json, name='get_all_vehicle_json'),
    path('owned-vehicles-json/<int:id>', get_owned_vehicle_json, name='get_owned_vehicle_json'),
    path('all-vehicles-xml/', get_all_vehicle_xml, name='get_all_vehicle_xml'),
    path('get-vehicles-xml/<int:id>/', get_vehicle_xml, name='get_one_vehicle_xml'),
    path('get-vehicles-json/<int:id>/', get_vehicle_json, name='get_one_vehicle_json'),
    path('get-vehicles-xml/<int:id>-<int:id2>/', get_vehicle_xml, name='get_vehicle_xml'),
    path('get-vehicles-json/<int:id>-<int:id2>/', get_vehicle_json, name='get_vehicle_json'),
    path('decrease_amount/<int:id>', decrease_amount, name='decrease_amount'),
    path('increase_amount/<int:id>', increase_amount, name='increase_amount'),
    path('delete/<int:id>',delete_this_item, name="delete"),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('increase-product-ajax/', increase_amount_ajax, name='increase_product_ajax'),
    path('decrease-product-ajax/', decrease_amount_ajax, name='decrease_product_ajax'),
    path('delete-item/',delete_item_with_id, name='delete_item_with_id'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Vehicle (models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    amount = models.IntegerField()
    description = models.TextField()
    image_link = models.TextField(default="", blank=True)

    def update_amount(self, new_amount):
        self.amount=new_amount
        self.save()
        
    def __str__(self):
        return str(self.name)+str(self.pk)

    

main/forms.py
from django.forms import ModelForm
from .models import Vehicle

class VehicleForm(ModelForm):
    class Meta : 
        model = Vehicle
        fields = ['name', 'amount', 'description', 'image_link']

main/views.py
import datetime
import json
from django.shortcuts import render
from django.http import HttpResponseNotFound, HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.core import serializers

from .forms import VehicleForm
from .models import Vehicle

from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages

from django.views.decorators.csrf import csrf_exempt

from django.contrib.auth.models import User



@login_required(login_url='/login')
def main(request):
    response = {'name':request.user.username,'class': 'PBP D'}
    all_vehicle = Vehicle.objects.filter(user = request.user)
    all_vehicle=list(all_vehicle)

    response['length']=len(all_vehicle)
    response['vehicle']= all_vehicle
    response['session']=request.COOKIES['last_login']
    # print(all_vehicle)
    
    return render(request, 'main.html', response)

@csrf_exempt
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse('main:main'))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request,'fail to login')
    return render(request, 'login.html', {})

@csrf_exempt
def register(request):
    # form = UserCreationForm()
    form = UserCreationForm(request.POST)

    # if form.method == 'POST':
        # form = form = UserCreationForm(request.POST)

        # if form.is_valid():
    if form.is_valid() and request.method == 'POST':

        form.save()
        
        response = HttpResponseRedirect(reverse('main:login'))
        messages.success(request, 'YEY!')

        response.set_cookie('last_login', str(datetime.datetime.now()))

        return response
    
    response = {'form':form}
    return render (request, 'register.html',response)

@csrf_exempt
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def add_vehicle(request):
    form = VehicleForm(request.POST or None)

    # print("reversed: "+reverse('main:main'))
    if form.is_valid() and request.method == "POST":
        vehicle = form.save(commit=False)
        vehicle.user = request.user
        vehicle.save()
        return HttpResponseRedirect(reverse('main:main'))
    
    response = {'form': form}
    return render(request, "add_vehicle.html", response)

def get_all_vehicle_json(request):
    print('11')
    all_vehicles = Vehicle.objects.all()
    return HttpResponse(serializers.serialize('json',all_vehicles), content_type="application/json")

@csrf_exempt
def get_owned_vehicle_json(request, id):
    print("id:",id)
    all_vehicles = Vehicle.objects.filter(user__pk=id)
    return HttpResponse(serializers.serialize('json',all_vehicles), content_type="application/json")


def get_all_vehicle_xml(request):
    all_vehicles = Vehicle.objects.all()
    return HttpResponse(serializers.serialize('xml',all_vehicles), content_type="application/json")

def get_vehicle_json(request,id,id2=-1):
    if(id2!=-1):
        all_vehicles = Vehicle.objects.all()
        all_vehicles=list(all_vehicles)
        temp=[]
        for v in all_vehicles:
            if id<= v.pk <=id2:
                temp+=[v]
        return HttpResponse(serializers.serialize('json',temp), content_type="application/json")
    else:
        print("in get vehicle json")
        all_vehicles = Vehicle.objects.filter(pk=id)
        return HttpResponse(serializers.serialize('json',all_vehicles), content_type="application/json")

def get_vehicle_xml(request,id,id2=-1):
    if(id2!=-1):
        all_vehicles = Vehicle.objects.all()
        all_vehicles=list(all_vehicles)
        temp=[]
        for v in all_vehicles:
            if id<= v.pk <=id2:
                temp+=[v]
        return HttpResponse(serializers.serialize('xml',temp), content_type="application/xml")
    else:
        all_vehicles = Vehicle.objects.filter(pk=id)
        return HttpResponse(serializers.serialize('xml',all_vehicles), content_type="application/xml")
    
def decrease_amount(request, id):
    temp = Vehicle.objects.get(id=id)
    if(temp.amount>0):
        temp.update_amount(temp.amount-1)
    return HttpResponseRedirect(reverse("main:main"))

def increase_amount(request, id):
    temp = Vehicle.objects.get(id=id)
    temp.update_amount(temp.amount+1)
    return HttpResponseRedirect(reverse("main:main"))

def delete_this_item(request, id):
    temp = Vehicle.objects.get(id=id)
    temp.delete()
    return HttpResponseRedirect(reverse("main:main"))

def get_product_json(request):
    print("in get_product_json")
    product_item = Vehicle.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    print("add_product_ajax")
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("price")
        description = request.POST.get("description")
        image_link = request.POST.get("image_link")
        user = request.user

        new_product = Vehicle(name=name, amount=amount , description=description, image_link=image_link ,user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def delete_item_with_id(request):
    if request.method=='POST':
        id = request.POST.get("id")
        temp = Vehicle.objects.get(pk=id)
        temp.delete()
        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def decrease_amount_ajax(request):
    print("in decrease amount ajax")
    if request.method == 'POST':
        print(request.body)
        id = request.body.get("id")
        print("id ",id)
        temp = Vehicle.objects.get(pk=id)
        if(temp.amount>0):
            temp.update_amount(temp.amount-1)
            print(temp)
        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def increase_amount_ajax(request):
    print("in increase views.py")
    if request.method == 'POST':
        id = request.POST.get("id")
        temp = Vehicle.objects.get(pk=id)
        print(temp)
        temp.update_amount(temp.amount+1)
        return HttpResponse(b"CREATED", status=201)
    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        print(request.user)

        new_product = Vehicle.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            description = data["description"]
        )

        new_product.save()
        print("masuk")

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    

main/templates/add_vehicle.html
{% extends "skeleton.html" %}

{% block content %}
<h1>ADD VEHICLES</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product"/>
            </td>
        </tr>
    </table>
</form>
{% endblock content %}

main/templates/login.html
{% extends "skeleton.html" %}
{% load static %}
{% block meta %}
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'test.css' %}"/>
{% endblock meta %}

{% block content %}
    <style>
        .login{
            background-color:#EEEEEE;
            width:40%;
            margin:20px;
            padding:5px 10px 20px 10px;
            color : #AABBCC;
        }
        body{
            background-color:#FCFBFB;
        }
        form{
            color:green;
        }
        .login h1{
            color:initial;
        }
    </style>
    <div class = "login">

        <h1>Login</h1>

        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td>Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>

                <tr>
                    <td></td>
                    <td><input class="btn login_btn" type="submit" value="Login"></td>
                </tr>
            </table>
        </form>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
            
        Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>

    </div>

{% endblock content %}

main/templates/main.html
{% extends "skeleton.html" %}
{% block meta %}

<style>

    body{
        margin: 0;
    }
    header{
        font-family: Arial,'Montserrat', Helvetica, sans-serif;
    }

    h1{
        font-weight: 700;
        padding:0px;
        font-size: 160px;
        margin-bottom: 20px;
        color: antiquewhite;
    }
    .home{
        padding-left: 5%;
        background-color: #205E4F;
        padding-top: 0.2%;
        padding-bottom: 0.2%;

    }
    .red{
        color: #F19A4D;
    }
    .home p{
        color: antiquewhite;
        margin-bottom: 100px;
        font-size: 48px;
        font-weight: 600;
    }
    .home .session{
        font-size:24px;
    }
    .navbar{
        display: flex;
        flex-direction: column;
        justify-content: space-around;
        align-items: center;
        
        position: sticky;
        top:0;

        background-color: antiquewhite;
        font-family: Arial,'Montserrat', Helvetica, sans-serif;
        padding:0% 0% 0% 0%;
    }

    .navbar #topnav{
        display: flex;
        flex-direction: row;
        justify-content: space-around;
        background-color: #F19A4D;
        width: 100%;
        padding-top: 1%;
        padding-bottom: 1%;
    }
    .navbar #botnav{
        display: flex;
        flex-direction: row;
        justify-content: space-around;
        width: 100%;
    }

    .navbar #navbarTitle{
        font-weight: 700;
        font-size: 28px;
        color: antiquewhite;
        text-decoration: none;
    }

    .navbar #navbarAbout{
        margin: 0px;
        position: sticky;
        top: 0;
        font-size: 24px;
        font-weight: 400;
        color: antiquewhite;
    }

    img{
        height: 40%;
        padding: 0px;
        margin: 0px;
    }
    .cards{
        background-color: #43B972;
        width: 100%;
        height: 1000px;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-flow: column wrap;
    }
    .cards h1{
        margin-bottom: 10%;
        margin-top: 0px;
    }
    #container{
        display: flex;
        justify-content: center;
        gap: 17px;
        flex-flow:wrap;
        padding: 0px;
        width: 100%px;
        margin-top: 0px;
        margin-bottom :3%;
    }

    .card{
        box-sizing: border-box;
        display: flex;
        background-color: #213150;
        width: 200px;
        height: 300px;
        justify-content: center;
        align-items: center;
        border-radius: 5%;
        flex-direction: column;
        box-shadow:inset;
    }
    .card #cardname{
        font-size: 28px;
        font-weight: 700;
        margin-bottom: 2%;
    }
    .card p{
        font-family: Arial,'Montserrat', Helvetica, sans-serif;
        font-weight: 500;
        color: antiquewhite;
        text-align: center;
        margin: 5px 0 5px 0;
    }
    .cardlast #cardname{
        font-size: 28px;
        font-weight: 700;
        margin-bottom: 2%;
    }
    .cardlast p{
        font-family: Arial,'Montserrat', Helvetica, sans-serif;
        font-weight: 500;
        color: antiquewhite;
        text-align: center;
        margin: 5px 0 5px 0;
    }
    .cards button{
        height : 50px;
        width:120px;
        border:0px;
        border-radius : 10px;
    }
    footer{
        display : flex;
        flex-direction:row;
        justify-content : space-around;
        padding : 2%;
        background-color:#F19A4D;
    }
    footer button{
        height : 50px;
        width:120px;
        border:0px;
        border-radius : 10px;
    } 
    .cardlast{
        box-sizing: border-box;
        display: flex;
        background-color: #AABBCC;
        width: 200px;
        height: 300px;
        justify-content: center;
        align-items: center;
        border-radius: 5%;
        flex-direction: column;
        box-shadow:inset; 
        background-color:#000000;
        color:#FFFFFF;
    }
    </style>

    <title>We Want Vehicles</title>

{% endblock meta %}
{% block content %}

    <body>
        <header>
            <div class="home">
                <h1>We Want<br/><span class="red">Vehicles</span></h1>
                <p>Vehicle database</p>
                <p class="session">session : {{session}}</p>
            </div>
        </header>
        <div class="navbar">
            <div id="topnav">
                <a href = "" id="navbarTitle">We Want Vehicles</span></a>
                <p id="navbarAbout">About Us</p>
            </div>
            <div id ="botnav">
                <p>Nama : {{name}}</p>
                <p>Kelas : {{class}}</p>
            </div>
        </div>
        
        <div class = "cards">
            <h1>VEHICLES</h1>
            <h2 id="panjang">Terdapat {{length}} item pada aplikasi ini</h2>
            <div id = "container">
                {% for v in vehicle %}
                    {% if forloop.last %}
                    <div class="cardlast">
                        <p id="cardname">{{v.name}}</p>
                        <img src={{v.image_link}} alt="{{v.name}}">
                        <a href = "{% url 'main:decrease_amount' v.id %}">
                            <button>-</button>
                        </a>
                        <p>Amount : {{v.amount}}</p>
                        <a href = "{% url 'main:increase_amount' v.id %}">
                            <button>+</button>
                        </a>
                        <p>{{v.description}}</p>
                        <br/>
                        <a href = "{% url 'main:delete' v.id %}">
                            <button>delete</button>
                        </a>
                        
                    </div>
                    {% else %}
                    <div class="card">
                        <p id="cardname">{{v.name}}</p>
                        <img src={{v.image_link}} alt="{{v.name}}">
                        <a href = "{% url 'main:decrease_amount' v.id %}">
                            <button>-</button>
                        </a>
                        <p>Amount : {{v.amount}}</p>
                        <a href = "{% url 'main:increase_amount' v.id %}">
                            <button>+</button>
                        </a>
                        <p>{{v.description}}</p>
                        <br/>
                        <a href = "{% url 'main:delete' v.id %}">
                            <button>delete</button>
                        </a>
                        
                    </div>
                    {% endif %}
                {% endfor %}
                </div>
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <form id="form" onsubmit="return false;">
                                {% csrf_token %}
                                <div class="mb-3">
                                    <label for="name" class="col-form-label">Name:</label>
                                    <input type="text" class="form-control" id="name" name="name"></input>
                                </div>
                                <div class="mb-3">
                                    <label for="price" class="col-form-label">Price:</label>
                                    <input type="number" class="form-control" id="price" name="price"></input>
                                </div>
                                <div class="mb-3">
                                    <label for="description" class="col-form-label">Description:</label>
                                    <textarea class="form-control" id="description" name="description"></textarea>
                                </div>
                                <div class="mb-3">
                                    <label for="description" class="col-form-label">Description:</label>
                                    <textarea class="form-control" id="image_link" name="image_link"></textarea>
                                </div>
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
                        </div>
                    </div>
                </div>
            </div>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product by AJAX</button>
            <a href ="{% url 'main:logout' %}"><button>Log Out</button></a>
        </div>

        <footer>
            <a href = "{% url 'main:get_all_vehicle_json' %}">
                <button>Vehicle all JSON</button>
            </a>
            <a href = "{% url 'main:get_all_vehicle_xml' %}">
                <button>Vehicle all XML</button>
            </a>
            
        </footer>

<script>
    async function getProducts() {
        return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
    }

    let length =0;

    async function refreshProducts() {
        document.getElementById("container").innerHTML = ""
        const products = await getProducts()
        
        let htmlString =""
        let idx=0
        products.forEach((item) => {
            if(idx==products.length-1){
                //alert("item id:"+item.pk)
                /*
                htmlString += `\n<tr class="cardlast">
                    <td>${item.fields.name}</td>
                    <td><button id='-${item.pk}'  onclick="decreaseProduct(${item.pk});">-</button>${item.fields.amount}<button id='+${item.pk}'  onclick="increaseProduct(${item.pk});">+</button></td>
                    <td>${item.fields.description}</td>
                    <td><button id='button-${item.pk}'  onclick="deleteProduct(${item.pk});">delete</button></td>
                </tr>` 
                */
                htmlString+=`<div class="cardlast">
                    <p id="cardname">${item.fields.name}</p>
                    <img src=${item.fields.image_link} alt=${item.fields.name}>

                    <button id="+${item.pk}" onclick="increaseProduct(${item.pk});">+</button>
                    <p>Amount : ${item.fields.amount}</p>
                    <button id="-${item.pk}" onclick="decreaseProduct(${item.pk});">-</button>
                    <p>{{v.description}}</p>
                    <br/>
                    <button id='button-${item.pk}'  onclick="deleteProduct(${item.pk});">delete</button>
                    
                </div>`
            }else{
                /*
                htmlString += `\n<tr>
                    <td>${item.fields.name}</td>
                    <td><button id='-${item.pk}'  onclick="decreaseProduct(${item.pk});">-</button>${item.fields.amount}<button id='+${item.pk}'  onclick="increaseProduct(${item.pk});">+</button></td>
                    <td>${item.fields.description}</td>
                    <td><button id='button-${item.pk}' onclick="deleteProduct(${item.pk});">delete</button></td>
                </tr>` 
                */
                htmlString+=`<div class="card">
                    <p id="cardname">${item.fields.name}</p>
                    <img src=${item.fields.image_link} alt=${item.fields.name}>

                    <button id="+${item.pk}" onclick="increaseProduct(${item.pk});">+</button>
                    <p>Amount : ${item.fields.amount}</p>
                    <button id="-${item.pk}" onclick="decreaseProduct(${item.pk});">-</button>
                    <p>{{v.description}}</p>
                    <br/>
                    <button id='button-${item.pk}'  onclick="deleteProduct(${item.pk});">delete</button>
                    
                </div>`
            }
            idx+=1
        })
        length = idx;
        document.getElementById("panjang").innerHTML="Terdapat "+length+" item pada aplikasi ini"
        document.getElementById("container").innerHTML = htmlString
    }

    refreshProducts()

    function addProduct() {
        fetch("{% url 'main:add_product_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector("#form"))
        }).then(refreshProducts)
        document.getElementById("form").reset()
        console.log("end add")
        return false
    }

    document.getElementById("button_add").onclick = addProduct

    function deleteProduct(id){

        const formData = new FormData()
        formData.append("id", id)

        fetch("{% url 'main:delete_item_with_id' %}",{
            method: "POST",
            body: formData
        }).then(refreshProducts)

        return false
    }

    function increaseProduct(id){

        const formData = new FormData()
        formData.append("id", id)

        fetch("{% url 'main:increase_product_ajax' %}",{
            method: "POST",
            body: formData
        }).then(refreshProducts)

        return false
    }

    function decreaseProduct(id){

        const formData = new FormData(document.querySelector('#form'))
        formData.append("id", id)
        
        fetch("{% url 'main:decrease_product_ajax' %}",{
            method: "POST",
            body: formData
        }).then(refreshProducts)
    
        return false
    }


</script>
{% endblock content %}

main/templates/register.html
{% extends "skeleton.html" %}
{% block meta %}
    <title>Register</title>
    <style>
        .judul-form{
            display:flex;
            flex-direction:column;
            align-items:center;
        }
        .badan{
            display:flex;
            flex-direction:column;
            align-items:flex-start;
            margin-left:100px;
        }
        h1{
            font-family:Arial;
            color:#000000;
            font-size:200%;
        }
        .container{
            width:100%;
            font-family: Arial,'Montserrat', Helvetica, sans-serif;
            display : flex;
            flex-direction: column;
            align-items:center;
            background-color:#EEEEEE;
            padding:20px;
        }
        .submit{
            border-radius:4%;
            padding:1% 5% 1% 5%;
            border:0px;
            background-color:#8EC63F;
            color:#FFFFFF;
        }
    
        .form{
            display : flex;
            flex-direction: column;
            justify-content:center;
            margin-bottom:10%;
            color:#071E22;
            font-size:14px;
        }
    
        input{
            border-radius:5%;
        }
    
        body{
            background-color:#FCFBFB;
        }
    
    
    </style>
{% endblock meta %}

{% block content %}
    
    <div class="badan">
        <div class="judul-form">
            <div class="Register">
                <h1> Register </h1>
            </div>
            <div class = "container">
                    <form  method="POST" class="form">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type = "submit" value="Register" class="submit" name="submit">
                    </form>
                {% for m in messages %}
                    <p>{{m}}</p>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}